modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="echovoids"
version="1.0.0"
displayName="EchoVoids"
displayURL="https://github.com/ImpulsiveLad"
credits="meow meow meow meow"
authors="Lassie<3"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.echovoids]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration